sudo: required
services: 
  - docker

before_install:
  - docker build -t thanhlam/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true thanhlam/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-832743809411"
  bucket_path: "docker"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY